# Count genes for each species

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX orth: <http://purl.org/net/orth#>

SELECT (COUNT(?gene) AS ?count) ?taxid ?label
WHERE {
  ?group a orth:OrthologsCluster ;
         orth:inDataset <https://ncbi.nlm.nih.gov/homologene/> ;
         orth:hasHomologousMember ?gene .
  ?gene obo:RO_0002162 ?taxid .
  ?taxid rdfs:label ?label .
}
ORDER BY DESC(?count)
